services:
  ats:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ats
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - /home/admin/Projects/ats/data:/var/www/html/data:rw
      - /home/admin/Projects/ats/backend:/var/www/html/backend:rw
    environment:
      - APP_ENV=production